# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1740b524290d61bac8aa4e04b92160c4ff3ad5acf6b09fd3d3e0fdb6a47149204eb205a25b0f90a3d6ce92a07adc8a77ea33b1c59389e999cf50adac77170e46

test:
  secret_key_base: e3d6d1f1040808969e9c3f86dc56f7ae32a87b0e0ca68be641eeced6b63617b27dc61c1c7e42d838af2e1d5ab8b2b309783a41d516be9b4c956418b4b9547099

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
